name: mal3ab
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter
  # State management
  get: ^4.7.3

  # Date and time
  jiffy: any
  intl: any

  # Networking
  http: any

  # Images
  cached_network_image: any
  image_picker: any

  # Animations
  show_up_animation: any
  auto_animated: any

  # Google Maps and location
  flutter_polyline_points: any
  google_maps_flutter: ^2.17.1
  geolocator: any
  geocoding: any

  # Firebase and notifications
  firebase_messaging: any
  firebase_core: any
  flutter_local_notifications: any
  cloud_firestore: any

  # Local storage
  sqflite: ^2.4.2
  shared_preferences: any
  path: any

  # QR codes
  qr_flutter: any
  # UI
  grouped_list: any
  url_launcher: any
  dropdown_search: any
  badges: any

  # Icons
  flutter_svg: ^2.3.0
  font_awesome_flutter: any
  fluttericon: any

  # Functional programming
  dartz: any

  # Google authentication
  google_sign_in: any

  # Responsive development
  responsive_builder: any

  # Image picker
  image_pickers: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.4.0
  pinput: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter:


  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/


  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/static/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
          weight: 700
    - family: BarlowCondensed
      fonts:
        - asset: assets/fonts/Barlow_Condensed/BarlowCondensed-Regular.ttf
        - asset: assets/fonts/Barlow_Condensed/BarlowCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow_Condensed/BarlowCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Barlow_Condensed/BarlowCondensed-Bold.ttf
          weight: 700


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/mal3ablogo.png 

  adaptive_icon_foreground: assets/images/foreground.png
  adaptive_icon_background: "#00C853"
